title: Women Techmakers Rio de Janeiro
description:  O Google empenha-se em desenvolver um ambiente de trabalho inclusivo no mundo todo. Com esse objetivo, o Women Techmakers foi criado para incentivar e apoiar qualquer pessoa cis, trans, binária ou não-binária que se identifique com o gênero feminino, perseguirem seus sonhos e se melhorarem como profissionais em um espaço seguro e profissional. O Women Techmakers Rio de Janeiro é uma comunidade independente, dentro do GDG Rio de Janeiro. 
show_downloads: false
theme: jekyll-theme-cayman

# Includes an icon in the footer for each username you enter
footer-links:
  email: rio.wtm@gmail.com
  facebook: https://www.facebook.com/wtmRio/
  flickr: https://www.flickr.com/photos/145156315@N06/
  github: https://github.com/wtmrio
  twitter: https://twitter.com/WTMRio
  youtube: https://www.youtube.com/channel/UCRor3pBXIRAUf8RX3h5lV-A
  medium: https://medium.com/wtmrio
